services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --sql_mode="STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: learn_go
    volumes:
      - ~/mnt-data/mysql/data:/var/lib/mysql
